[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors https://www.facebook.com; default-src 'self'; script-src 'self https://www.facebook.com/'; style-src 'self https://www.facebook.com/'"

[build]
NODE_ENV = "prod"
base="frontend/"
publish="frontend/out/"
command="npm run export"
